#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "src/.*\.js$\|src/.*\.vue$")


if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo -e "\n\033[41;37m Validating Javascript:\033[0m\n "

# Check for eslint
ESLINT="npm run eslint"
${ESLINT} &> /dev/null
if [[ "$?" == 1 ]]; then
  echo -e "\t\033[31mPlease run npm install eslint\n\033[0m"
  exit 1
fi

# for FILE in $STAGED_FILES
# do
# done
$ESLINT $STAGED_FILES "--silent"

if [[ "$?" == 0 ]]; then
  echo -e "\t\033[32mESLint Passed \033[0m"
else
  echo -e "\t\033[31mESLint Failed \033[0m"
  echo -e "\t\033[31mPlease fix it\033[0m\n"
  PASS=false
fi

echo -e "\n\033[32mJavascript validation completed!\033[0m\n"

if ! $PASS; then
  # echo -e "\033[32mPlease fix it\033[0m\n"
  exit 1
else
  echo -e "\033[32mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
